db:
  image: mongo:latest
web:
  build: .
  volumes:
    - ./server:/app/server
    - ./grunt:/app/grunt
    - ./Gruntfile.js:/app/Gruntfile.js
    - ./bower.js:/app/bower.js
    - ./package.json:/app/package.json
    - ./tsd.json:/app/tsd.json
  ports:
    - "3000:3000"
    - "35729:35729"    
  links:
    - db